### ISSUE TITLE
What's this and how do I use it?

### ISSUE THREAD

**Issue by bucaran** [daneeel/bar#1]
Hi, I realized dev may be slow or even "ded" :smile:, but I was wondering what this is all about?

What is lemonbar? Is it a command line prompt?

**Comment by daneeel** [comment]
Hi! :)

Lemonbar is a bar for X11 that shows text that is piped into it on screen.
https://github.com/LemonBoy/bar

This project was an attempt to make configuration easier, so that the user would only need to write the scripts for individual blocks. I was too lazy to finish it yet, though. It's currently running on my system, but it's very messy and limited.

I suggest you look into one of these instead, all similar ideas, but implemented better:
https://github.com/muse/Captain
https://github.com/DelusionalLogic/bard
https://github.com/OkayDave/barr/

I might even switch to using barr and stop this project altogether soon.

**Comment by bucaran** [comment]
@daneeel Forgive my ignorance, I looked at the first link, but it's still not very clear. What is a "bar"? Is it a desktop application? Is the bar displayed inside my terminal?

Sorry for all the unrelated questions.

**Comment by daneeel** [comment]
It's like a panel in your desktop environment, usually shown at the top or bottom of the screen. You can use your own scripts to show various information on it.

**Comment by bucaran** [comment]
@daneeel Thanks a lot, that makes sense. A fish plugin for this would be nice indeed :)
